### ISSUE TITLE
Support fish shell

### ISSUE THREAD

**Issue by WarFox** [kuanyui/hexo.el#15]
This works great!

However, it doesn't have support on the fish shell, because all the commands use `&&` that works in `bash` and `zsh`. 

Fish uses `; and` combination instead of `&&`

I replace all the `&&` combination like the following in `hexo.el`
```
hexo clean && hexo generate && hexo server --debug
```
to `; and` combination for this to work

```
hexo clean ; and hexo generate ; and hexo server --debug
```

I'm wondering if we can support  both `bash` and `fish` somehow

**Comment by kuanyui** [comment]
Sorry for late. I think it would be better if add a customizable variable for specify your bash (or zsh) path, instead of add support for each shell?

**Comment by WarFox** [comment]
Thanks for your reply! 
Yes, that should do. Then based on that variable, we can choose the separator.

**Comment by LdBeth** [comment]
I prefer a customizable shell command string, 'cause `hexo clean` every time is not efficient and my machine is quite slow.

**Comment by WarFox** [comment]
Please check my pull-request https://github.com/kuanyui/hexo.el/pull/16

I have added support for both customizable shell-command-separator and customizable shell command string for hexo.

**Comment by kuanyui** [comment]
Now you can use `(setq hexo-posix-compatible-shell-file-path "/bin/bash")` to specify bash/zsh path. I decide take this way instead of make separator customizable is for portability concerning.

And sorry for late for such a long time.

**Comment by WarFox** [comment]
great! that's a better idea.. I shall try this one and confirm here

**Comment by WarFox** [comment]
I tried the following in my `spacemacs/user-config`. but it doesn't seem to work
```elisp
  (setq shell-file-name "fish")
  (setq hexo-posix-compatible-shell-file-path "/usr/local/bin/fish")
```

I'll try working on this to find a solution, it may be something to do with my settings

**Comment by WarFox** [comment]
my bad with the previous configuration

The following setting partially works, for example `hexo-new` command works
```elisp
  (setq hexo-posix-compatible-shell-file-path "/bin/bash")
```

But `hexo-server-run` still fails, as it is still not forcing posix

**Comment by kuanyui** [comment]
Sorry, my fault. No fixed.

**Comment by kuanyui** [comment]
Sorry, my carelessness. Now should be fixed.

**Comment by WarFox** [comment]
great! works for me! 👍 
closing the issue!
