### ISSUE TITLE
How do I specify a custom repo-root-dir?

### ISSUE THREAD

**Issue by Hunter-Github** [kuanyui/hexo.el#3]
There is no such option in the Hexo option group.

**Comment by kuanyui** [comment]
Oops... OK, now I just added a new optional argument to `hexo`, you can define your function like this to open a specified hexo repo directly:

``` lisp
(defun hexo-my-blog ()
    (interactive)
    (hexo "~/my-blog/"))
```

M-x `hexo-my-blog` to use.
