### ISSUE TITLE
bloglist is empty

### ISSUE THREAD

**Issue by mydearxym** [kuanyui/hexo.el#5]
love your work!

but M-x hexo shows me a empty list 

![image](https://cloud.githubusercontent.com/assets/6184465/14764429/cb2089aa-09e9-11e6-8d8c-29bbe6287638.png)

![image](https://cloud.githubusercontent.com/assets/6184465/14764430/d82613d6-09e9-11e6-8611-23416103645c.png)

**Comment by kuanyui** [comment]
Please give me more details. Show me your `tree` output.

**Comment by mydearxym** [comment]
sorry, it's my own config issue.
