### ISSUE TITLE
can it support org file ?

### ISSUE THREAD

**Issue by orangercat** [kuanyui/hexo.el#6]
can it support org file in major mode .thanks

**Comment by kuanyui** [comment]
Please elaborate your request. I've never tried to use org file in Hexo, don't know any information about it.

**Comment by kuanyui** [comment]
For example, what is the format of a org file used in Hexo (article title, date time, tags, categories....etc)? How to make hexo support org file?

**Comment by orangercat** [comment]
thanks!
i install plugin [hexo-renderer-org](https://github.com/CodeFalling/hexo-renderer-org), it support for `file.org` when i `hexo generate` 
but `hexo.el` cant support `file.org` in `hexo-mode`
the template of format for `file.el`is

```
#+TITLE: Hello,orgmode
#+DATE: <2015-11-15 Sun 17:00>
#+TAGS: emacs, orgmode, hexo
#+LAYOUT: post
#+CATEGORIES: orgmode
* Orgmode
** Why org
#+BEGIN_SRC js
console.log('hello');
#+END_SRC
我编不下去了。。
```

**Comment by kuanyui** [comment]
- The possible values of `#+LAYOUT:` are `post/draft`? Any else?
- Can tag name contain spaces? How to?
- Is these properties able to use quote? e.g. `#+TAGS: "Emacs Lisp", "Open Source"`, `#+TITLE: "Hello World!"`
- What is the article format in `pages/` ?

I have no time to find all possible value (because I don't and won't use org-mode to write blog) , so please provide me a more detailed example, so that I can add org-mode support for `hexo.el` when I have free time.

**Comment by orangercat** [comment]
thanks,
1, it didn't change files in HEXO dir.
2, when i find file in _post dir , i think it is in post status
3, i use org-mode for `file.org` in these properties

```
#+TITLE: 完美解决 Mac 下 Vim/Emacs 的输入法切换问题
#+DATE: <2015-11-02 Mon 16:29>
#+TAGS: tool,project
#+CATEGORIES: PROJECT
```

so usually use these quotes `#+TITLE`,`#+DATE`,`#+TAGS`,`#+CATEGORIES`

**Comment by kuanyui** [comment]
> thanks,
> 1, it didn't change files in HEXO dir.

I cannot understand what you're talking about.

> 2, when i find file in _post dir , i think it is in post status

So the `#+LAYOUT: post` in article file are unnecessary at all (for determine if it is a `post` or `draft`)?

> 3, i use org-mode for file.org in these properties

You still didn't tell me if  `"quote symbole"` is unavailable in org-mode + hexo?

**Comment by orangercat** [comment]
1.  nerver mind,ingore it .
2. i determine it by  _post dir or draft dir
3.  in org-mode quote text use

```
#+BEGIN_QUOTE
引用的文字
#+END_QUOTE
```

**Comment by kuanyui** [comment]
`3` -> I mean a tag (`#+TAGS:`) contains spaces.

**Comment by orangercat** [comment]
`#+TAGS: hexo,project,hexo-asset-image`
it contains a space between `:` and `hexo`

**Comment by kuanyui** [comment]
OMG....
I mean **a tag which contains space(s)**. e.g. `Emacs Lisp`

**Comment by orangercat** [comment]
sorry
i never use space in tags, i test several time
if use`#+TAGS: Emacs Lisp` will be  `EamcsLisp`in web
so i test`#+TAGS: Emacs&nbspLisp` i can be `Emacs Lisp` as i wish

**Comment by kuanyui** [comment]
Hmmm... That's bizarre. Thanks for your information. I think I will add org-mode support in weeks (when I have time).

**Comment by orangercat** [comment]
thanks !

**Comment by kuanyui** [comment]
@orangercat What are the results when you use 
- `#+TAGS: "Emacs Lisp"`
- `#+TAGS: "Emacs_Lisp"`
- `#+TAGS: Emacs_Lisp`

**Comment by orangercat** [comment]
#+TAGS：Emacs Lisp

**Comment by orangercat** [comment]
let me test

**Comment by kuanyui** [comment]
And multiple tags. e.g.:
    `#+TAGS: "Emacs Lisp", "Programming Language"`
    `#+TAGS: "Emacs_Lisp", "Programming_Language"`
    `#+TAGS: Emacs_Lisp, Programming_Language`

**Comment by orangercat** [comment]
> #+TAGS: "Emacs Lisp"
> `"EMACSLISP"`
> 
> #+TAGS: "Emacs_Lisp"
> `"EMACS_LISP"`
> 
> #+TAGS: Emacs_Lisp
> `EMACS_LISP`
> 
> #+TAGS: "Emacs Lisp", "Programming Language"
> `"EMACSLISP", "PROGRAMMINGLANGUAGE"`
> 
> #+TAGS: "Emacs_Lisp", "Programming_Language"
> `"EMACS_LISP", "PROGRAMMING_LANGUAGE"`
> 
> #+TAGS: Emacs_Lisp, Programming_Language
> `EMACS_LISP, PROGRAMMING_LANGUAGE`

**Comment by driftcrow** [comment]
@orangercat I have almost done a branch  [orgmodesupport](https://github.com/kuanyui/hexo.el/pull/8) for org-mode support,works fine for myself,you can use it and tell me if you have any problem.

**Comment by kuanyui** [comment]
Sorry for such late. Now you can try org-mode supports.

To make hexo-new works properly, please check out https://github.com/kuanyui/hexo.el#org-mode-support for configuration
