### ISSUE TITLE
hexo-command-revert-tabulated-list: Invalid function: hexo-mode-only

### ISSUE THREAD

**Issue by orangercat** [kuanyui/hexo.el#7]
when i use blog-mode , 

```
hexo-command-revert-tabulated-list: Invalid function: hexo-mode-only
```

**Comment by kuanyui** [comment]
Please elaborate your issue. What is blog-mode?

**Comment by orangercat** [comment]
i use

```
(defun hexo-my-blog ()
    (interactive)
    (hexo "~/my-blog/"))
```

and `m-x hexo-my-blog`

`hexo-command-revert-tabulated-list: Invalid function: hexo-mode-only`
in command

**Comment by kuanyui** [comment]
That's bizarre... Does this error still exist when you use `emacs -Q` ?

**Comment by kuanyui** [comment]
And, how did you install `hexo-mode`? MELPA?
Because basically this error message shouldn't appear at all. That's so bizarre.

**Comment by orangercat** [comment]
yes i install `hexo-mode` via

```
dotspacemacs-additional-packages '(
                                      hexo
                                      )
```

**Comment by kuanyui** [comment]
I just found `hexo` in MELPA stuck at version `20160423.817` (obviously, 4 months ago...But `hexo.el` updated in 2 weeks ago) and cannot be installed... It seems MELPA's problem. Maybe you can throw an issue to MELPA.

Before they solve the problem, you still can install `hexo.el` manually.
![md4](https://cloud.githubusercontent.com/assets/1370070/17670015/9e93ffcc-6342-11e6-9c57-b5edb98f2e95.png)

**Comment by orangercat** [comment]
fine.
i check my hexo verison
![image](https://cloud.githubusercontent.com/assets/4132725/17685250/ea632b9c-6394-11e6-9863-3f58a7c79210.png)
it's ver20160801.

**Comment by kuanyui** [comment]
Why.... OAO...
BTW, do you still encounter the same issue if you install `hexo.el` manually?

**Comment by kuanyui** [comment]
I don't know why, I suddenly found that I cannot install any package in MELPA currently... (All packages shows "Not found")
Tested on two of my system, with `emacs -Q`, so I cannot reproduce your issue.
![wwwwwwwww1](https://cloud.githubusercontent.com/assets/1370070/17688731/6e41620c-63b4-11e6-859b-1d787d9d5f1e.png)

**Comment by orangercat** [comment]
i use mirror url 

```
(setq configuration-layer--elpa-archives
      '(("melpa-cn" . "http://elpa.zilongshanren.com/melpa/")
        ("org-cn"   . "http://elpa.zilongshanren.com/org/")
        ("gnu-cn"   . "http://elpa.zilongshanren.com/gnu/")))
```

its more stable. gnu.org crashed several days ago 

smae issue install manually

**Comment by kuanyui** [comment]
Please `M-x toggle-debug-on-error`, run `M-x hexo` then paste the error message, otherwise I cannot guess the reason.

**Comment by orangercat** [comment]
```
Debugger entered--Lisp error: (invalid-function hexo-mode-only)
  hexo-mode-only(nil 1 #(" Status Filename Title Date ▲ Categories Tags " 0 1 (display (space :align-to 3)) 1 7 (tabulated-list-column-name "Status" help-echo "Click to sort by column" mouse-face highlight keymap (keymap (follow-link . mouse-face) (13 . tabulated-list-sort) (mouse-2 . tabulated-list-col-sort) (mouse-1 . tabulated-list-col-sort) (header-line keymap (mouse-2 . tabulated-list-col-sort) (mouse-1 . tabulated-list-col-sort)))) 7 8 (display (space :align-to 10) face fixed-pitch) 8 16 (tabulated-list-column-name "Filename" help-echo "Click to sort by column" mouse-face highlight keymap (keymap (follow-link . mouse-face) (13 . tabulated-list-sort) (mouse-2 . tabulated-list-col-sort) (mouse-1 . tabulated-list-col-sort) (header-line keymap (mouse-2 . tabulated-list-col-sort) (mouse-1 . tabulated-list-col-sort)))) 16 17 (display (space :align-to 51) face fixed-pitch) 17 22 (tabulated-list-column-name "Title" help-echo "Click to sort by column" mouse-face highlight keymap (keymap (follow-link . mouse-face) (13 . tabulated-list-sort) (mouse-2 . tabulated-list-col-sort) (mouse-1 . tabulated-list-col-sort) (header-line keymap (mouse-2 . tabulated-list-col-sort) (mouse-1 . tabulated-list-col-sort)))) 22 23 (display (space :align-to 100) face fixed-pitch) 23 29 (face bold tabulated-list-column-name "Date" help-echo "Click to sort by column" mouse-face highlight keymap (keymap (follow-link . mouse-face) (13 . tabulated-list-sort) (mouse-2 . tabulated-list-col-sort) (mouse-1 . tabulated-list-col-sort) (header-line keymap (mouse-2 . tabulated-list-col-sort) (mouse-1 . tabulated-list-col-sort)))) 29 30 (display (space :align-to 112) face fixed-pitch) 30 40 (tabulated-list-column-name "Categories" help-echo "Click to sort by column" mouse-face highlight keymap (keymap (follow-link . mouse-face) (13 . tabulated-list-sort) (mouse-2 . tabulated-list-col-sort) (mouse-1 . tabulated-list-col-sort) (header-line keymap (mouse-2 . tabulated-list-col-sort) (mouse-1 . tabulated-list-col-sort)))) 40 41 (display (space :align-to 129) face fixed-pitch) 41 45 (tabulated-list-column-name "Tags" help-echo "Click to sort by column" mouse-face highlight keymap (keymap (follow-link . mouse-face) (13 . tabulated-list-sort) (mouse-2 . tabulated-list-col-sort) (mouse-1 . tabulated-list-col-sort) (header-line keymap (mouse-2 . tabulated-list-col-sort) (mouse-1 . tabulated-list-col-sort)))) 45 46 (display (space :align-to 130) face fixed-pitch)))
  hexo-command-revert-tabulated-list()
  hexo()
  call-interactively(hexo record nil)
  command-execute(hexo record)
  helm-M-x(nil "hexo")
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)

```

**Comment by kuanyui** [comment]
1.For manual installation, is this error still existed when you use `emacs -Q` and following setting? 

``` lisp
(add-to-list 'load-path "~/.emacs.d/git/hexo.el")
(require 'hexo)
```

2.What is your Emacs version?

I totally cannot reproduce your problem. I use `emacs -Q` and the above two line settings, run `M-x hexo` without any error even warning...

Tested on GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.16.7) of 2016-05-12 on linux-4yaw

**Comment by orangercat** [comment]
1. i use`(hexo :location (recipe :fetcher github :repo "kuanyui/hexo.el"))` to sync ur code
2. my emacs version is GNU Emacs 24.5.1 (x86_64-apple-darwin15.6.0, NS apple-appkit-1404.47) 
   and i use emacs.app with GUI  and spacemacs

**Comment by kuanyui** [comment]
> 1. i use`(hexo :location (recipe :fetcher github :repo "kuanyui/hexo.el"))` to sync ur code

Wait, please install `hexo.el` manually. We still have not found where is the point, so don't use package managers, which make the whole problem more complex.

However, if you **have tried**:
1. Removing the `hexo.el` installed via MELPA & `package.el`
2. Install `hexo.el` manually by yourself.
3. Use `emacs -Q` to start Emacs, paste: `(add-to-list 'load-path "~/.emacs.d/git/hexo.el") (require 'hexo)` in `*scratch*`, and `M-x eval-buffer` then `M-x hexo`

...And still encounter the same error, I cannot help you. Because I've tested the above steps on both of my system, but still cannot reproduce the error message you've encountered... Sorry...

**Comment by orangercat** [comment]
thanks... i use `(add-to-list 'load-path "~/.emacs.d/git/hexo.el") (require 'hexo)`
now its ok. but still has error via MELPA. never mind ,its not a critical problem. thanks!

**Comment by kuanyui** [comment]
Oh yeah glad to heard that. At least it's a proof that hexo.el itself has no problem.

**Comment by orangercat** [comment]
yeah  thanks for your code

**Comment by eailfly** [comment]
Hi. I have the same issue here too, I install use spacemacs so I install hexo with

    (hexo :location(recipe
              :fetcher github
              :repo "kuanyui/hexo.el"
        ))

since I use spacemacs, I have nowhere to use the manual way

**Comment by kuanyui** [comment]
Please try later. I don't sure where the problem is...
