### ISSUE TITLE
[Ask for features] delete posts in hexo-mode, and specify a template when create a new post

### ISSUE THREAD

**Issue by LdBeth** [kuanyui/hexo.el#9]
It will be helpful if the files in `/scaffolds` can be used as templates when a argument is passed to `hexo-new`.
Also, though it is not a necessary feature for me, enable the ability to delete posts/drafts makes it easier to manage files.

**Comment by kuanyui** [comment]
In fact, `hexo.el` never deal with `/scaffolds` at all. That's processed by hexo itself.

Delete file... Hmm, ok, I think that's good.

**Comment by kuanyui** [comment]
Ok I've add delete function. See README for information. Please try it :)
